server:
  port: 80
spring:
  thymeleaf:
#    prefix: classpath:/templates/view/
#    suffix: .html
    cache: false    # 开发环境不用开启缓存,方便ctrl+shift+F9 进行重新编译,无需重启服务
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: utf-8
    excluded-view-names:
    mode: HTML
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
